apiVersion: batch/v1
kind: Job
metadata:
  name: gcsfuse-npi-benchmark-template
  labels:
    app: gcsfuse-npi-benchmark
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: gcsfuse-npi-benchmark
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      restartPolicy: Never
      containers:
        - name: benchmark
          image: "image-placeholder"
          args: ["--mount-path=/data"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: gcsfuse-csi
              mountPath: /data
      serviceAccountName: "ksa-placeholder"
      volumes:
        - name: gcsfuse-csi
          csi:
            driver: gcsfuse.csi.storage.gke.io
            volumeAttributes:
              bucketName: test-bucket
